package markdown

// At-command handling (Req 11.2–11.10).
//
// Influence recognizes four `@`-commands in the Markdown_Editor / Rich_Renderer,
// split along a fundamental axis:
//
//   - EDIT-TIME authoring aids — `@link` and `@heading`. These are resolved once,
//     at insertion time, into ordinary markdown; nothing persists as a directive.
//     The backend's job is only to supply the data the editor presents: for
//     `@link`, the selectable list of *other* Polygons in the tenant (empty, with
//     an indicator, when none — Req 11.2/11.3); for `@heading`, the fixed set of
//     markdown heading-style choices (Req 11.4).
//
//   - RENDER-TIME directives — `@toc` and `@children`. These persist in the
//     stored markdown as directives and are regenerated by the Rich_Renderer from
//     the *current* page structure every time the page renders (Req 11.9). `@toc`
//     expands to a table of contents built from the page's current headings
//     (empty when there are none — Req 11.5/11.6); `@children` expands to a list
//     of the current Polygon's direct child Polygons (empty when none —
//     Req 11.7/11.8).
//
// This file owns the render-time expansion of `@toc`/`@children` and the
// edit-time data helpers. It deliberately takes the candidate/child Polygon
// lists as parameters rather than reaching into a repository: looking those up
// is a repo concern, and keeping this package free of that dependency lets the
// same expansion logic be exercised in isolation. The on-screen toolbar icons
// (Req 11.10) are a frontend concern; this file exposes the command catalog and
// each command's icon identifier so the frontend (task 23.2) can render them
// without re-deriving the list.

import (
	"fmt"
	"strings"
)

// AtCommand identifies one of the four recognized `@`-commands.
type AtCommand string

const (
	// CmdLink is the edit-time `@link` command: insert a link to another
	// Polygon in the tenant (Req 11.2).
	CmdLink AtCommand = "@link"
	// CmdHeading is the edit-time `@heading` command: insert a markdown
	// heading in a chosen style (Req 11.4).
	CmdHeading AtCommand = "@heading"
	// CmdTOC is the render-time `@toc` directive: a table of contents built
	// from the page's current headings (Req 11.5).
	CmdTOC AtCommand = "@toc"
	// CmdChildren is the render-time `@children` directive: a list of the
	// current Polygon's direct child Polygons (Req 11.7).
	CmdChildren AtCommand = "@children"
)

// CommandKind distinguishes the two resolution times of an `@`-command.
type CommandKind int

const (
	// EditTime commands are authoring aids resolved to markdown at insertion
	// time (`@link`, `@heading`).
	EditTime CommandKind = iota
	// RenderTime commands persist as directives and are regenerated from the
	// current page structure at render (`@toc`, `@children`).
	RenderTime
)

// CommandInfo describes one `@`-command for consumers such as the editor
// toolbar. Icon is a stable identifier the frontend maps to an actual glyph;
// keeping it here (rather than in the frontend) ensures the typed command and
// its on-screen icon stay in lockstep (Req 11.10).
type CommandInfo struct {
	// Command is the typed form, e.g. "@toc".
	Command AtCommand
	// Kind is when the command resolves (edit-time vs render-time).
	Kind CommandKind
	// Icon is a stable icon identifier for the frontend to render.
	Icon string
	// Label is a short human-readable name for the command.
	Label string
}

// Commands returns the catalog of every recognized `@`-command together with
// its kind, icon identifier, and label, in a stable order. The frontend uses
// this to render a toolbar icon for each command in addition to the typed form
// (Req 11.10); no command may exist without an on-screen icon, so every entry
// carries a non-empty Icon.
func Commands() []CommandInfo {
	return []CommandInfo{
		{Command: CmdLink, Kind: EditTime, Icon: "at-link", Label: "Link"},
		{Command: CmdHeading, Kind: EditTime, Icon: "at-heading", Label: "Heading"},
		{Command: CmdTOC, Kind: RenderTime, Icon: "at-toc", Label: "Table of contents"},
		{Command: CmdChildren, Kind: RenderTime, Icon: "at-children", Label: "Children"},
	}
}

// --- Edit-time: @heading ----------------------------------------------------

// HeadingStyle is one selectable markdown heading style offered by `@heading`.
type HeadingStyle struct {
	// Level is the heading level, 1–6.
	Level int
	// Label is a short human-readable name, e.g. "Heading 1".
	Label string
	// Prefix is the markdown that opens a heading of this level, e.g. "# ".
	Prefix string
}

// HeadingStyles returns the fixed set of markdown heading-style choices the
// editor presents when a User enters `@heading` (Req 11.4). CommonMark ATX
// headings run from level 1 to level 6; the list is returned shallow-to-deep.
func HeadingStyles() []HeadingStyle {
	styles := make([]HeadingStyle, 0, 6)
	for level := 1; level <= 6; level++ {
		styles = append(styles, HeadingStyle{
			Level:  level,
			Label:  fmt.Sprintf("Heading %d", level),
			Prefix: strings.Repeat("#", level) + " ",
		})
	}
	return styles
}

// Heading renders the markdown for a chosen heading style applied to text. It
// is what the editor inserts once a `@heading` choice is made (Req 11.4). Levels
// outside 1–6 are clamped into range so the result is always a valid ATX
// heading; the text is trimmed of surrounding whitespace and newlines so a
// single clean heading line is produced.
func Heading(level int, text string) string {
	if level < 1 {
		level = 1
	}
	if level > 6 {
		level = 6
	}
	return strings.Repeat("#", level) + " " + strings.TrimSpace(text)
}

// --- Edit-time: @link -------------------------------------------------------

// LinkCandidate is one Polygon the User may link to via `@link`. The markdown
// package does not query the tenant for these; the caller (a repo/service
// layer) supplies the list of *other* Polygons in the tenant. ID is the
// target's Record_ID in canonical form; Name is its current display name.
type LinkCandidate struct {
	ID   string
	Name string
}

// LinkOptions is the data the editor presents when a User enters `@link`
// (Req 11.2): the selectable list of link candidates plus, when that list is
// empty, an indicator explaining that no linkable Polygons exist (Req 11.3).
type LinkOptions struct {
	// Candidates is the selectable list of other Polygons to link to. It is
	// empty when there are none.
	Candidates []LinkCandidate
	// Empty is true exactly when Candidates is empty.
	Empty bool
	// Indicator is a human-readable message shown when Empty is true, and ""
	// otherwise.
	Indicator string
}

// BuildLinkOptions turns a caller-supplied list of candidate Polygons into the
// selectable list the editor shows for `@link` (Req 11.2). When candidates is
// empty it returns an empty list carrying an indicator that no linkable
// Polygons exist (Req 11.3). A nil slice and an empty slice are treated
// identically. The returned Candidates slice is a fresh copy, so the caller's
// slice is never aliased or mutated.
func BuildLinkOptions(candidates []LinkCandidate) LinkOptions {
	if len(candidates) == 0 {
		return LinkOptions{
			Candidates: nil,
			Empty:      true,
			Indicator:  "No linkable Polygons exist in this tenant.",
		}
	}
	out := make([]LinkCandidate, len(candidates))
	copy(out, candidates)
	return LinkOptions{Candidates: out, Empty: false}
}

// LinkMarkdown renders the markdown a `@link` selection inserts: a labelled
// link to the target Polygon by Record_ID, in the platform's internal link
// form influence://polygon/{id} (see design "Storage model"). The visible label
// is the candidate's current name.
func LinkMarkdown(c LinkCandidate) string {
	return fmt.Sprintf("[%s](influence://polygon/%s)", c.Name, c.ID)
}

// --- Render-time: @toc ------------------------------------------------------

// ExpandTOC builds the markdown for a `@toc` directive from a page's current
// headings (Req 11.5). The heading set is derived from Sections(content): every
// section whose Level is 1–6 contributes one TOC entry, in document order,
// nested by heading level. When the page has no headings the result is the
// empty string — an empty table of contents (Req 11.6).
//
// Because the entries are recomputed from content on every call, a change to the
// page's heading set is reflected the next time the directive is expanded, which
// is exactly the regeneration behavior Req 11.9 requires.
func ExpandTOC(content []byte) string {
	secs := Sections(content)
	// Find the shallowest heading level present so indentation is relative to
	// the top of *this* page rather than absolute heading levels.
	minLevel := 0
	for _, s := range secs {
		if s.Level >= 1 && (minLevel == 0 || s.Level < minLevel) {
			minLevel = s.Level
		}
	}
	if minLevel == 0 {
		// No headings: an empty table of contents (Req 11.6).
		return ""
	}

	var b strings.Builder
	for _, s := range secs {
		if s.Level < 1 {
			continue
		}
		indent := strings.Repeat("  ", s.Level-minLevel)
		b.WriteString(indent)
		b.WriteString("- ")
		b.WriteString(s.Heading)
		b.WriteByte('\n')
	}
	return b.String()
}

// --- Render-time: @children -------------------------------------------------

// ChildPolygon is one direct child Polygon of the current Polygon, as supplied
// by the caller for `@children` expansion. Resolving the child set is a repo
// concern, so the markdown package receives it rather than querying for it. ID
// is the child's Record_ID (canonical form); Name is its current display name.
type ChildPolygon struct {
	ID   string
	Name string
}

// ExpandChildren builds the markdown for a `@children` directive from the
// current Polygon's direct child Polygons (Req 11.7). Each child becomes a
// bulleted internal link to that Polygon by Record_ID, in the order supplied.
// When the Polygon has no children the result is the empty string — an empty
// list (Req 11.8).
//
// The caller passes the current child set on every call, so a change to that
// set is reflected the next time the directive is expanded, satisfying the
// regeneration requirement (Req 11.9).
func ExpandChildren(children []ChildPolygon) string {
	if len(children) == 0 {
		// No children: an empty list (Req 11.8).
		return ""
	}
	var b strings.Builder
	for _, c := range children {
		b.WriteString("- ")
		b.WriteString(LinkMarkdown(LinkCandidate{ID: c.ID, Name: c.Name}))
		b.WriteByte('\n')
	}
	return b.String()
}
